version: '3.8'

services:
  dev:
    container_name: appdev
    image: app-dev:latest
    init: true
    build:
      context: .
      target: app-dev
      dockerfile: ./Dockerfile
    # command: sh -c "yarn start:dev"
    command: sh -c "yarn refresh-schema && yarn seed-data && yarn start:dev"
    # command: sh -c "bash"
    # tty: true
    ports:
      - 3000:3000
    networks: [app-net]
    volumes:
      - .:/usr/src/app
      # This adds an anonymous volume for node_modules, because some node module installs are host specific like bcrypt.
      # NOTE: doing this means that any node module updates done from outside the container will have no effect in the
      # container's node modules.
      - /usr/src/app/node_modules
    depends_on:
      - db

  prod:
    container_name: appprod
    image: app-prod:latest
    init: true
    build:
      context: .
      target: app-prod
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 3003:3000
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    networks:
      - app-net

  db:
    container_name: appdb
    image: postgres:11-alpine
    init: true
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    networks:
      - app-net
networks:
  app-net:
